version: '3.4'

x-mutagen:
    sync:
        defaults:
            ignore:
                vcs: true
        code:
            ignore:
                paths:
                    - "./docker"
                    - "node_modules"
                    - "tmp"
                    - "private"
                    - "assets"
            alpha: "../"
            beta: "volume://code"
            mode: "two-way-resolved"
            permissions:
                defaultOwner: "id:501"
                defaultGroup: "id:20"
                defaultFileMode: 0644
                defaultDirectoryMode: 0755

            configurationAlpha:
                permissions:
                    defaultOwner: "id:501" # user
                    defaultGroup: "id:20" # user
            configurationBeta:
                permissions:
                    defaultOwner: "id:1000" # www-data
                    defaultGroup: "id:1000" # www-data
                    defaultFileMode: 0644
                    defaultDirectoryMode: 0755
