services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $screenshotsPath: '%kernel.project_dir%/var/screenshots/test/'

    App\Tests\:
        resource: '../tests/*'
        exclude:
            - '../tests/bootstrap.php'
