services:
    _defaults:

        autowire: true
        autoconfigure: true

       # Bind not used parameters will raise an exception
        bind:
             string $webmasterEmail: 'webmaster@email.ext'
#            string $kernelProjectDir: '%kernel.debug%'
#            string $kernelLogDir: '%kernel.logs_dir%'
#            string $kernelEnvironment: '%kernel.environment%'
#            string $screenshotsPath: '%kernel.project_dir%/var/screenshots/test/'
#            string $mailHogBaseUrl: 'http://localhost:8025'
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Tests\:
        resource: '../tests'
        exclude:
            - '../tests/bootstrap.php'
